### ISSUE TITLE
quick change between char-mode and word-mode

### ISSUE THREAD

**Issue by julienJean99** [mm--/ace-mc#4]
so I've been using ace jump for a bit now and I'm often frustrated because I can't use the quick change like the original ace-mode (C-c C-c to quickly change from char-mode to word-mode and vice-versa) so I have to quit out and make the correct shortcut?

good job otherwise tho.

**Comment by mm--** [comment]
Interesting. That's a feature of `ace-jump-mode` that I wasn't aware of. If I have time this weekend, I'll see if there's an easy fix to adding that. It might be as simple as adding advice to `ace-jump-quick-exchange`.

**Comment by julienJean99** [comment]
thank you for taking the time to look a it.

**Comment by mm--** [comment]
Sorry it took me so long to get around to this. `C-c C-c` for quick exchange should now work.
Let me know if there are any issues with it.
